name = "synpixel/fusion_reflex"
version = "0.1.0"
description = "A port of react-reflex for Fusion 0.3"
authors = ["synpixel"]
repository = "https://github.com/synpixel/fusion-reflex"
license = "MIT"
includes = ["src", "README.md", "LICENSE.md", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
